apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp-deployment
  labels:
    app: pyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
        - name: pyapp
          image: public.ecr.aws/v9m7i5p8/pyapp:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pyapp-nodeport-service
  labels:
    app: pyapp
spec:
  type: NodePort
  selector:
    app: pyapp
  ports:
    - port: 8080
      targetPort: 8080

